In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('전국문화축제표준데이터.csv', encoding='cp949')
df.head()

,축제명,개최장소,축제시작일자,축제종료일자,축제내용,주관기관명,주최기관명,후원기관명,전화번호,홈페이지주소,관련정보,소재지도로명주소,소재지지번주소,위도,경도,데이터기준일자,제공기관코드,제공기관명
0,구미라면축제,구미역 일원,2026-11-06,2026-11-08,이색라면 레스토랑 및 `갓 튀긴 라면` 팝업스토어 운영 등,경상북도 구미시,경상북도 구미시,NaN,054-480-2652,https://www.gumiramyun.com/,NaN,NaN,경상북도 구미시 원평동 124-23,36.129403,128.331413,2026-06-16,B551011,한국관광공사
1,김천김밥축제,직지문화공원 및 사명대사공원 일원,2026-10-23,2026-10-25,김밥플레이리스트(축하공연)+꼬달이 돌잡이 등,경상북도 김천시,경상북도 김천시,NaN,053-965-0910,https://gimbapcity.kr/,NaN,경상북도 김천시 대항면 황악로 1189-52,경상북도 김천시 대항면 운수리 산44-1,36.103084,127.992908,2026-06-16,B551011,한국관광공사
2,임실N치즈축제,임실치즈테마파크+임실치즈마을+임실읍 일원,2026-10-08,2026-10-11,임실N치즈 쭉쭉늘려 내치즈+디저트 퐁뒤체험+국가대표 임실N치즈 대형 쌀피자,임실N치즈축제제전위원회,임실N치즈축제제전위원회,문화체육관광부+농림축산식품부+한국관광공사+전북특별자치도+전북특별자치도 임실군,063-643-3900,www.imsilfestival.com,NaN,전북특별자치도 임실군 성수면 도인2길 50,전북특별자치도 임실군 성수면 도인리 689,35.633102,127.301258,2026-06-16,B551011,한국관광공사
3,여주오곡나루축제,여주 신륵사관광지 일원,2026-10-23,2026-10-25,여주쌀 가마솥 비빔밥+군고구마 기네스+여주 본두리 낙화놀이+여주 흔암리 쌍용거 줄다...,여주세종문화관광재단,경기도 여주시,NaN,031-881-9694,https://www.yjfestival.or.kr/,NaN,경기도 여주시 신륵사길 7,경기도 여주시 천송동 297-1,37.300017,127.656746,2026-06-16,B551011,한국관광공사
4,강동선사문화축제,서울 암사동 유적,2026-10-16,2026-10-18,개폐막식+축하공연+개막 드론쇼+폐막 불꽃쇼+거리퍼레이드+강동선사 노래자랑+자치회관 ...,서울특별시 강동구,서울특별시 강동구,NaN,02-3425-5240,https://www.gdsunsa.com/,NaN,서울특별시 강동구 올림픽로 875 (암사동),서울특별시 강동구 암사동 139-2,37.559854,127.130832,2026-06-16,B551011,한국관광공사

In [3]:
df['축제명']

0            구미라면축제
1            김천김밥축제
2           임실N치즈축제
3          여주오곡나루축제
4          강동선사문화축제
           ...
1295     제68회 백제문화제
1296       마곡사 신록축제
1297       불갑산상사화축제
1298         법성포단오제
1299    제33회 성산일출축제
Name: 축제명, Length: 1300, dtype: str

In [4]:
name_list = df['축제명'].to_list()
name_list

['구미라면축제',
 '김천김밥축제',
 '임실N치즈축제',
 '여주오곡나루축제',
 '강동선사문화축제',
 '목포항구축제',
 '진안홍삼축제',
 '장수한우랑사과랑축제',
 '서산해미읍성축제',
 '계룡軍문화축제',
 '통영한산대첩축제',
 '포항국제불빛축제',
 '한산모시문화제',
 '태화강마두희축제',
 '해운대모래축제',
 '이천도자기축제',
 '대전사이언스페스티벌',
 '진해군항제',
 '영동난계국악축제',
 '천안흥타령축제',
 '보령머드축제',
 '금산세계인삼축제',
 '무주반딧불축제',
 '김제지평선축제',
 '함평나비대축제',
 '정남진장흥물축제',
 '담양대나무축제',
 '광주 추억의 충장축제',
 '경북영주 풍기인삼축제',
 '안동국제탈춤페스티벌',
 '문경찻사발축제',
 '하동야생차문화축제',
 '진주남강유등축제',
 '산청한방약초축제',
 '얼음나라화천 산천어축제',
 '평창효석문화제',
 '춘천마임축제',
 '음성품바축제',
 '논산딸기축제',
 '순창장류축제',
 '영암왕인문화축제',
 '보성다향대축제',
 '인천펜타포트 락 페스티벌',
 '부평풍물대축제',
 '울산옹기축제',
 '세종한글축제',
 '부산국제록페스티벌',
 '동래읍성역사축제',
 '광안리어방축제',
 '대구치맥페스티벌',
 '광주김치축제',
 '청송사과축제',
 '고령대가야축제',
 '밀양아리랑대축제',
 '화성뱃놀이축제',
 '연천구석기축제',
 '안성맞춤 남사당 바우덕이축제',
 '시흥갯골축제',
 '수원화성문화제',
 '부천국제만화축제',
 '평창송어축제',
 '철원 한탄강 얼음트레킹 축제',
 '정선아리랑제',
 '강릉커피축제',
 '김해분청도자기축제',
 '강진 불금불파',
 '곡성세계장미축제',
 '담양 대나무축제',
 '보성다향대축제',
 '함평 나비대축제',
 '신안 섬 수선화 축제',
 '광주김치축제',
 '광주 펫크닉',
 'GAC 공연예술축제 그라제',
 '광주사운드파크페스티벌',
 '광주프린지페스티벌',
 '광주비엔날레',
 '광주스트릿컬처페스타',
 '부산불꽃축제',
 '부산국제록페스티벌',
 '부산바다축제',
 '부산밀페스티벌',
 '부산항축제',
 '부산원도심활성화축제',
 '부산시민의종 타종식',
 '여주도자기축제',
 '여주오곡나루축제',
 '함양연암문화제',
 '천령문화제',
 '제21회 함양산삼축제',
 '의령 리치리치 페스티벌',
 '의령 홍의장군축제',
 '한겨울 분천 산타마을 축제',
 '봉화송이축제',
 '봉화은어축제',
 '2026 삼강나루주막축제',
 '2026 금당야행',
 '범우리 비어 페스티벌',
 '2026 회룡포봄꽃축제',
 '2026 용궁순대축제',
 '2026 예천활축제',
 '한여름밤 김천페스타',
 '평화로상가축제',
 '김천부곡맛고을 축제',
 '김천황금시장 김장양념축제',
 '김천평화시장 떡축제',
 '2026 김천포도축제',
 '2026 연화지 벚꽃 축제',
 '김천김밥축제',
 '강진하맥축제',
 '강진수국길축제',
 '전라병영성축제',
 '강진청자축제',
 '강진만 춤추는 갈대축제',
 '제19회_정남진_장흥_물축제',
 '2025 장흥 회령포 이순신 축제',
 '제18회_정남진_장흥_물축제',
 '2024 장흥 회령포 이순신 축제',
 '제17회_정남진_장흥_물축제',
 '제6회_회령포_문화축제',
 '제16회_정남진_장흥_물축제',
 '제15회_정남진_장흥_물축제',
 '2026 장흥 회령포 이순신 축제',
 '광양 K-POP 페스티벌',
 '광양전통숯불구이축제',
 '광양전어축제',
 '백운산국사봉철쭉축제',
 '광양천년동백축제',
 '광양매화축제',
 '장수 한우랑 사과랑 축제',
 '장수 쿨밸리 페스티벌',
 '금산삼계탕축제',
 '금산세계인삼축제',
 '금산보곡산골 산벚꽃축제',
 '무창포 신비의 바닷길 축제',
 '제29회 보령머드축제',
 '보령 AMC 국제모터 페스티벌',
 '2025 보령 국가유산야행',
 '제28회 보령머드축제',
 '보령 AMC 국제모터 페스티벌',
 '주산 벚꽃축제',
 '무창포 주꾸미 도다리 축제',
 '제2회 보령시 겨울방학 석탄축제',
 '2024 천북 굴축제',
 '제10회 은행마을 단풍 축제',
 '2024 보령 김축제',
 '제5회 섬의 날 행사',
 '제16회 전국해양스포츠제전',
 '제27회 보령머드축제',
 '2024 보령 어린이 대축제',
 '제3회 보령AMC모터페스티벌',
 '무창포 신비의 바닷길 주꾸미 도다리 대잔치',
 '대천겨울바다사랑축제',
 '제20회 성주산단풍축제',
 '2023 보령 김축제',
 '제26회 보령머드축제',
 '제2회 보령AMC모터페스티벌',
 '대천해수욕장 조개구이 한마당',
 '2026년 보령 국가유산야행',
 '2026년 충주시립우륵국악단 어린이 음악극<호랑이와 곶감>',
 '2026년 충주시립택견단 단오맞이 옛택견판',
 '2026년 충주시립우륵국악단 토요상설공연<국악버스킹>',
 '정선아리랑제',
 '2026 에코 아트페어',
 '2026 춘천연극제',
 '제38회 춘천인형극제',
 '제13회 춘천영화제',
 '2026 춘천마임축제',
 '포은문화제',
 '용인시민의 날 연계 축제 행사',
 '처인성문화제',
 '하남이성산성문화축제',
 '하남뮤직페스티벌',
 '제26회 복사골청소년예술제',
 '제41회 부천복사골예술제',
 '제18회 시민어울림한마당',
 '2026 대전 서구 아트페스티벌',
 '2025 비엔날레 문화콘서트4',
 '2025 비엔날레 문화콘서트3',
 '2025 비엔날레 문화콘서트2',
 '2025 비엔날레 문화콘서트1',
 '2025 비엔날레 문화콘서트5',
 '고려산 진달래 꽃구경',
 '크리스마스 문화축제',
 '제14회 연수 능허대 문화축제',
 '제6회 송도해변축제',
 '새봄맞이 연수한마음 축제',
 '비슬산 참꽃문화제',
 '비슬산 참꽃문화제',
 '정월대보름 달맞이문화제',
 '정월대보름 달맞이문화제',
 '정월대보름 달맞이문화제',
 '비슬산 참꽃문화제',
 '달구벌목민관축제',
 '미소&행복 구민축제',
 '가족사랑 아이스축제',
 '오감만족+ 어린이날 큰 잔치',
 '달성토성마을축제',
 '와룡산 와~봄 축제',
 '해맞이축제',
 '정관생태하천학습문화축제',
 '기장미역다시마축제',
 '기장멸치축제',
 '철마한우불고기축제',
 '제23회 사상강변축제',
 '제7회 연제고분판타지축제',
 '강서 낙동강30리 벚꽃축제(2026년)',
 '2026 정월대보름 달집태우기 행사',
 '2025 금정산성축제',
 '다대포 선셋 영화축제',
 '장림항 부네치아 아트프리마켓',
 '감천문화마을 골목축제',
 '제41회 해운대 달맞이온천축제',
 '2026 제21회 해운대 모래축제',
 '서면 빛축제',
 '동작댄스데이',
 '세계불꽃축제with 버스킹',
 '동작서커스데이',
 'K-분식페스티벌 &나루터영화제',
 '도심속바다축제',
 '구로G페스티벌(아시아문화축제)',
 '마곡위시빌리지',
 '제24회 허준축제',
 '강서문화야행',
 '제3회 허준인트로 축제',
 '민관연계협력 축제',
 '오구오구 어린이 버스킹 시즌4',
 '2026년 우장산 그린빛 페스타',
 '2026년 마곡문화거리버스킹',
 '제10회 겸재문화예술제',
 '2026년 강서봄빛페스타',
 '상산 김도연 특별전',
 '맥주축제',
 '선농대제',
 '동대문구 봄꽃축제',
 '동대문페스티벌',
 '제4회 합천황토한우축제',
 '제5회 황매산억새축제',
 '제30회 황매산철쭉제',
 '제2회 별내린마을, 별쿵축제',
 '고스트파크 축제',
 '2026 대장경기록문화축제',
 '제7회 수려한합천영화제',
 '제42회 대야문화제',
 '합천벚꽃마라톤대회',
 '거창크리스마스트리문화축제',
 '거창한마당대축제',
 '거창국제연극제',
 '빛으로 만나는 문화축제',
 '2026경남고성공룡세계엑스포',
 '우포늪 생명길 걷기대회',
 '우포따오기와 함께하는 비사벌 문화제',
 '제9회 창녕양파마늘가요제',
 '제15회 산토끼와 따오기가 함께하는 창작동요제',
 '창녕낙동강유채축제',
 '부곡온천축제',
 '제65회 3.1민속문화제',
 '양산삽량문화축전',
 '양산웅상회야제',
 '물금벚꽃축제',
 '원동매화축제',
 '2026 통영한산대첩축제',
 '진주국제농식품박람회',
 '진주탈춤한마당',
 '진주 전국민속 소힘겨루기대회',
 '진주 M2(뮤직&미디어)페스티벌',
 '진주논개제',
 '코리아드라마페스티벌',
 '개천예술제',
 '진주남강유등축제',
 '그때&그랬지청도유천문화거리축제',
 '2026정월대보름민속한마당',
 '2026청도세계코미디아트페스티벌',
 '2026청도반시축제',
 '군위 바비큐축제',
 '삼국유사 문화축전',
 '김수환추기경 사랑과 나눔 문화축전',
 '군위 삼장군단오축제',
 '2025년 섬 겨울꽃 축제',
 '섬 아자니아 꽃 축제',
 '2025 ABFF 컨벤션 대한민국 분재 대전',
 '2025년 섬 함초 축제',
 '섬 새우젓축제',
 '2025년 국제꽃장식대회',
 '섬 맨드라미 축제',
 '여름새우란 전시',
 '섬 홍도 원추리꽃 축제',
 '2025년 섬 크로코스미아꽃 축제',
 '제6회 섬 수국축제',
 '섬 밴댕이축제',
 '섬 병어축제',
 '섬 깡다리축제',
 '섬 낙지축제',
 '신안 샴막 예술 축제',
 '라벤더 축제',
 '옥도 작약 꽃 축제',
 '신안 세계 김밥페스타',
 '100+4 피아노섬 축제',
 '섬 간재미축제',
 '2025 섬 튤립축제',
 '2025년 섬 수선화축제',
 '2025 섬 홍매화축제',
 '제29회 무안연꽃축제',
 '2026 무안 도리포 유채꽃 축제',
 '2026 무안겨울숭어축제',
 '제5회 무안YD페스티벌',
 '제3회 무안갯벌낙지축제',
 '2025 몽탄 코스모스 축제',
 '2025 운남에서 돈세고 놀자 축제',
 '제11회 무안황토갯벌축제',
 '제28회 무안연꽃축제',
 '해넘이해맞이축제',
 '흑석산 힐링축제',
 '황산 연호보리축제',
 '두륜산 왕벚꽃나무 막걸리 축제',
 '해남 새봄 새김치 담그기 축제',
 '해남 공룡대축제',
 '해남미남축제',
 '명량대첩축제',
 '달마고도 힐링걷기',
 '서편제 보성소리축제',
 '보성다향대축제',
 '옥정호 벚꽃축제',
 '임실도자기축제',
 '의견문화제와 함께하는 임실N펫스타',
 '임실N치즈축제',
 '임실N장미축제',
 '산타축제',
 '제30회 무주반딧불축제',
 '제27회 칠갑산장승문화축제',
 '2026 청양 고추구기자 축제(제27회)',
 '제72회 백제문화제',
 '제24회부여서동연꽃축제',
 '제22회 백제고도 부여국화축제',
 '제71회 백제문화제',
 '제23회부여서동연꽃축제',
 '2025 부여국가유산 야행',
 '제70회 백제문화제',
 '제22회부여서동연꽃축제',
 '2026 양촌곶감축제',
 '2026 강경젓갈축제',
 '2026 연산대추축제',
 '2026 강경 국가유산 야행',
 '2026 한국유교문화축전',
 '2026 논산딸기축제',
 '생거진천농다리축제',
 '생거진천문화축제',
 '제30회 제천청풍호벚꽃축제',
 '2026년 재즈페스티벌 in 가평',
 '2026 김포 선셋 페스타',
 '2026 김포 벚꽃축제',
 '2026 김포 라베니체축제',
 '2026 김포 해병대문화축제',
 '2026 김포 아라마린페스티벌',
 '2026년 제8회 운정호수공원 불꽃축제',
 '2026년 파주포크페스티벌(본공연)',
 '2026년 파주포크페스티벌(전야제)',
 '2026 제 36회 율곡문화제',
 '제3회 파주 페어 북앤컬처',
 '제18회 DMZ 국제다큐멘터리 영화제',
 '2026 헤이리 판 페스티벌',
 '제30회 파주장단콩축제',
 '2026 구리 유채꽃 축제',
 '2026 장자호수 벚꽃마실',
 '2025 구리 빛 축제',
 '2025 구리 코스모스 축제',
 '2025 구리 유채꽃 축제',
 '2024 구리 코스모스 축제',
 '2024 구리 유채꽃 축제',
 '2023 구리 코스모스 한강예술제',
 '2023 구리 유채꽃 한강예술제',
 '제19회 구리 코스모스 축제',
 '제19회 구리 유채꽃 축제',
 '제18회 구리 코스모스 축제',
 '제18회 구리 유채꽃 축제',
 '제17회 구리 코스모스 축제',
 '제17회 구리 유채꽃 축제',
 '제16회 구리 코스모스 축제',
 '제16회 구리한강 유채꽃 축제',
 '제15회 구리 코스모스 축제',
 '제15회 구리한강 유채꽃 축제',
 '2026 과천공연예술축제',
 '2026 고양호수예술축제',
 '제38회 고양행주문화제',
 '제29회 성호문화제',
 '안산 벚꽃놀이터',
 '제12회 상록수문화제',
 '제11회 상록수문화제',
 '제10회 상록수문화제',
 '제9회 상록수문화제',
 '제8회 상록수문화제',
 '제7회 상록수문화제',
 '제6회 상록수문화제',
 '제5회 상록수문화제',
 '제4회 상록수문화제',
 '제3회 상록수문화제',
 '제2회 상록수문화제',
 '제1회 상록수문화제',
 '여르미오페스티벌',
 '여르미오페스티벌',
 '여르미오페스티벌',
 '여르미오페스티벌',
 '여르미오페스티벌',
 '여르미오페스티벌',
 '여르미오페스티벌',
 '여르미오페스티벌',
 '여르미오페스티벌',
 '안산국제거리극축제',
 '안산국제거리극축제',
 '안산국제거리극축제',
 '안산국제거리극축제',
 '안산국제거리극축제',
 '안산국제거리극축제',
 '안산국제거리극축제',
 '안산국제거리극축제',
 '안산국제거리극축제',
 '안산국제거리극축제',
 '안산국제거리극축제',
 '2026년 동두천 어린이날 축제',
 '2025 동두천무형문화대축제',
 '도심재생 야간축제',
 '동두천락페스티벌',
 '천사데이기념행사',
 '동두천시 자원봉사 축제',
 '동두천 청소년 별자리과학 축제',
 '왕방산 국제MTB대회',
 '2026 페스티벌 광명',
 '제34회 오리문화제',
 '광명동굴빛축제',
 '광명등문화축제',
 '구름산예술제',
 '2026 안양충훈벚꽃축제',
 '2025 제3회 안양일번가 넘버원 페스티벌',
 '2025 안양춤축제 ANYANG DANCE FESTIVAL',
 '2025 안양충훈벚꽃축제',
 '2024 제2회 안양일번가 넘버원 페스티벌',
 '2024 안양춤축제 ANYANG DANCE FESTIVAL',
 '2024 안양충훈벚꽃축제',
 '2023 안양춤축제 ANYANG DANCE FESTIVAL',
 '2023 광복78주년 광복기념음악회',
 '2023 안양충훈벚꽃축제',
 '2022 안양시민축제 <우선멈춤>',
 '2021 안양시민축제 <우선멈춤>',
 '2019 안양 시민축제',
 '2019 광복기념음악회',
 '2019 안양여성축제',
 '2019 안양충훈벚꽃축제',
 '2018 안양 시민축제',
 '2018 광복기념음악회',
 '2018 안양여성축제',
 '2018 안양충훈벚꽃축제',
 '2017 안양 시민축제',
 '2017 광복기념음악회',
 '2017 안양 아줌마축제',
 '2017 안양충훈벚꽃축제',
 '2016 제5회 안양공공예술프로젝트',
 '2016 안양 시민축제',
 '2016 광복기념음악회',
 '2016 안양 아줌마축제',
 '2015 안양 시민축제',
 '2015 안양 아줌마축제',
 '2014 안양시민축제',
 '2014 안양 아줌마축제',
 '우리가족 꼬마영웅 올림픽',
 '2026년 가을걷이 한마당',
 '반려동물 문화행사(페스티벌)',
 '튼튼쑥쑥 걷기대회',
 '식품제조 홍보 및 판매관',
 '2026 모두모여모란',
 '제5회 정자동 놀터축제 및 작품발표회',
 '사회복지페스티벌',
 '2026 파크콘서트',
 '제136주년 세계노동절 기념식 및 노동가족 음악문화제',
 '제31회 환경의 날 기념행사',
 '육아데이「한 여름밤의 꿈」',
 '지구촌 어울림 축제',
 '2026년 성남시 식품안전의 날',
 '성남 어린이날 행사',
 '2026 어린이날 해병대 고무보트 승선체험',
 '2026 성남 연등회',
 '제20회 청계산 철쭉축제',
 '2026 봄꽃 축제(봄이 왔서현)',
 '낭만톡톡 조합원 힐링의 밤',
 '2026년 판교마당바위 해맞이축제',
 '울산쇠부리축제',
 '울산쇠부리축제',
 '궁거랑 벚꽃 한마당',
 '울산고래축제',
 '2026년 울산병영3.1만세운동 제26회 재현행사',
 '2026 문화의거리 현대미술제',
 '2026년 외솔한글한마당',
 '2026 태화강마두희축제',
 '2026 유성온천문화축제',
 '2025 대청호 벚꽃축제',
 '제6회 대청호 벚꽃축제',
 '제5회 대청호 벚꽃축제',
 '제4회 대청호 벚꽃축제',
 '제3회 대청호 벚꽃축제',
 '제2회 대청호 벚꽃축제',
 '제1회 대청호 벚꽃축제',
 '양림 크리스마스 문화축제',
 '사직단오제',
 '사직연등축제',
 '고싸움놀이축제',
 '광주서창억새축제',
 '양동통맥축제',
 '제26회소래포구축제',
 '제36회 화도진축제',
 '제35회 화도진축제',
 '2023년 화수부두 축제',
 '제34회 화도진축제',
 '제33회 화도진축제',
 '동구문화예술한마당&막걸리페스티벌',
 '제30회 화도진축제',
 '제29회 화도진축제',
 '제28회 화도진축제',
 '제27회 화도진축제',
 '천을산 해맞이',
 '상화문학제',
 '동구 어울림한마당 축제',
 '동구 여름축제',
 '동구 봄축제',
 '팔공산 단풍축제',
 '용암산성 옥샘문화제',
 '팔공산 왕건축제',
 '안심창조밸리 연꽃마을 축제',
 '선덕여왕 숭모재',
 '팔공산 벚꽃축제',
 '제24회광안리어방축제',
 '제13회 낙동강 구포나루 축제',
 '동래읍성역사축제',
 '영도커피페스티벌',
 '영도다리축제',
 '부산고등어축제',
 '현인가요제',
 '광복로겨울빛트리축제',
 '부산자갈치축제',
 '부산국제영화제 전야제',
 '유라리 건맥축제',
 '강동선사문화축제',
 '2026 관악강감찬축제',
 '2026 그루브 인 관악',
 '2026 S1472 어린이주간',
 '2026 관악책빵축제',
 '2025 리딩데이',
 '2025 관악봄축제 관악힐링북페스타',
 '리딩데이:관악산책',
 '2024 관악강감찬축제',
 '2024 관악봄축제 HAPPY FESTIVAL',
 '2024 그루브 인 관악',
 '2023 관악겨울예술축제 : Winter Festival is Coming to Town',
 '2023 모두의 축제: 청춘 관악',
 '관악구 협치과제 다정다감 페스티벌',
 '2023 관악강감찬축제',
 '2023 어린이동화페스티벌',
 '2023 GIG Festival',
 '관악구 협치과제 이십세기 음악상점',
 '2023 관악어린이가족축제_관악봄봄',
 '관악구 협치과제 S1472 어린이주간',
 '2022 어린이동화페스티벌',
 '2022 관악강감찬축제',
 '그루브인관악 페스티벌',
 '2026 금천하모니축제',
 '은평의 봄',
 '종교연합바자회',
 '4.19혁명 국민문화제',
 '제22회 강북구 3·1독립운동 기념행사',
 '제17회 농업농촌사랑 푸른뜰 체험행사',
 '제16회 반딧불 곤충축제',
 '청남대가을축제',
 '청남대꽃문화축제 영춘제',
 '청남대 재즈토닉 페스티벌',
 '2026제천국제한방천연물산업엑스포',
 '간절곶 해맞이 축제',
 '울산울주세계산악영화제',
 '119안전문화축제',
 '태화강 대숲 납량축제',
 '울산뮤직페스티벌',
 '울산조선해양축제',
 '태화강마두희축제',
 '울산대공원 장미축제',
 '태화강국제재즈음악제',
 '울산고래축제',
 '울산옹기축제',
 '궁거랑 벚꽃 한마당',
 '울산공업축제',
 '태화강 국가정원 봄꽃축제',
 '울산쇠부리축제',
 '왕가의 산책',
 '2025년 인천도시역사관 어린이 특별전 <가자 갯벌도시>',
 '2025년 부평역사박물관 특별기획전 <도시기록법 : 우리가 부평을 기억하는 방법>',
 '이야기꽃이 피었습니다',
 '새봄맞이 연수한마음 축제',
 '2026 제물포웨이브 마켓',
 '2026 대한민국 라면 박람회',
 '연극<나의 아저씨>',
 '움직임 이후의 고요',
 '앉고 눕고 숨쉬며 살아가는 방법',
 '연극<고트 GOTT>',
 '2026 해양레저관광 박람회',
 '원도심골목길축제<가을:집대성>',
 '디저트베이커리 페스타',
 '청주 미식주 페스타',
 '오송화장품 뷰티산업엑스포',
 '청원생명축제',
 '세종대왕과 초정약수축제',
 '청주전통공예페스티벌',
 '동부창고페스타',
 '청주읍성큰잔치',
 '직지문화축제',
 '원도심골목길축제<여름:성안이즈백>',
 '국가유산 미디어아트',
 '한여름밤의 오싹 호러페스티벌',
 '힙한 청주 페스티벌 in 제조창',
 '청남대 재즈토닉',
 '도시농업페스티벌',
 '청주가 그린 green 페스티벌',
 '청주 정원박람회',
 '피크닉 콘서트',
 '청주국가유산야행',
 '원도심골목길축제<봄:중앙극장>',
 '청주 민족예술제',
 '청주예술제',
 '청주삼겹살대축제',
 '제3회 화성 루나 빛 축제',
 '2025 화성 학생동아리 축제',
 '정조효문화제 및 정조대왕능행차 공동재현',
 '제3회 도농 어울림 축제',
 '화성송산포도축제',
 '제15회 화성 뱃놀이 축제',
 '화성시 연등 음악 축제',
 '제16회 화성시 가족사랑축제',
 '거제몽돌해변불꽃축제',
 '장승포항송년불꽃축제',
 '거제도국제펭귄수영축제',
 '거제 섬꽃축제',
 '거제둔덕포도&한우축제',
 '거제맥주축제',
 '거제여름해양축제',
 '남부면 수국축제',
 '거제 옥포대첩 축제',
 '거제맹종대나무축제',
 '청송사과축제',
 '제8회의성슈퍼푸드마늘축제',
 '제18회산수유마을꽃맞이행사',
 '제2회남대천벚꽃축제',
 '제7회의성슈퍼푸드마늘축제',
 '2026 경산 반려문화축제',
 '제15회 경산대추축제 농산물한마당',
 '2026 경산갓바위소원성취축제',
 '2026 경산자인단오제',
 '정월대보름 시민한마당',
 '2026 해맞이행사',
 '영천보현산별빛축제',
 '영천보현산별빛축제',
 '2026 구미푸드페스티벌',
 '2026 구미라면축제',
 '안동국제탈춤페스티벌',
 '차전장군 노국공주축제',
 '2026년 변산비치펍 시즌2',
 '2026년 제13회 부안마실축제',
 '2025년 변산해넘이축제',
 '2025년 제13회 설숭어축제',
 '2025년 부안붉은노을축제',
 '2025년 제17회 부안곰소젓갈축제',
 '2025년 변산비치펍',
 '2025년 제12회 부안마실축제',
 '2025년 제7회 개암동벚꽃축제',
 '2026 진안홍삼축제',
 '제16회 진안고원 수박축제',
 '제22회 진안고원 운장산 고로쇠축제',
 '제8회 진안고원 김치보쌈축제',
 '제96회 남원 춘향제',
 '익산주얼팰리스보석대축제',
 '익산문화유산야행',
 '익산천만송이국화축제',
 '익산서동축제',
 '2026 제14회 군산시간여행축제',
 '서산어리굴젓축제',
 '서산국화축제',
 '서산해미읍성축제',
 '삼길포우럭축제',
 '서산6쪽마늘축제',
 '팔봉산 감자축제',
 '류방택 별축제',
 '해미벚꽃축제',
 '제39회 지용제',
 '2025 화천토마토축제',
 '2026 얼음나라 화천 산천어축제',
 '동해무릉제',
 '해변 뮤직 페스티벌',
 '이천도자기축제',
 '이천체험문화축제',
 '2025 부평풍물대축제',
 '2024 부평풍물대축제',
 '2023 부평풍물대축제',
 '2022 부평풍물대축제',
 '2021 부평풍물대축제',
 '2020 부평풍물대축제',
 '2026 부평풍물대축제',
 '떡볶이 페스티벌',
 '금호강 바람소리길축제',
 '금호강 정월대보름축제',
 '새해 해맞이 행사',
 '강남페스티벌',
 '가로수길 디자인위크',
 'G-KPOP 콘서트',
 '악기거리축제',
 '말죽거리축제',
 '서리풀페스티벌',
 '반포서래 한불음악축제',
 '도구로 가을 축제',
 '잠원나루축제',
 '2026 영등포 여의도 봄꽃축제',
 '2027 신년 해맞이 축제',
 '노원달빛산책',
 '댄싱노원 거리페스티벌',
 '노원수제맥주축제',
 '세종조치원복숭아축제',
 '세종한글축제',
 '2025 세종 빛트리 축제',
 '세종낙화축제',
 '2025년 제7회 양주 천만송이 천일홍 축제',
 '2025 제8회 양주 회암사지 왕실 축제',
 '김해시평생학습과학축제',
 '가야문화축제',
 '김해분청도자기축제',
 '2026 영해3.18독립만세문화제',
 '제29회 영덕대게축제',
 '포항국제불빛축제',
 '포항스틸아트페스티벌',
 '포항 흥해 국가유산야행',
 '포항장기유배문화제',
 '호미곶한민족해맞이축전',
 '장성읍 영천 막걸리 축제',
 '동화면 동화나라 버베나 축제',
 '북쪽하늘아래 산나물축제',
 '황룡면 뱃나드리 축제',
 '삼계면 민관군 화합 전통문화체험 축제',
 '장성 어울림음악회',
 '백양사 산사음악회',
 '백양사 고불매 선매향 축제',
 '황룡강 음악 힐링 축제',
 '황룡강 가을꽃축제',
 '진원 산동리 유채꽃 축제',
 '대한민국 국향대전',
 '물놀이 페스타',
 '나비대축제',
 '겨울빛축제',
 '홍성남당항 대하축제',
 '홍성남당항 새조개축제',
 '홍성글로벌바비큐페스티벌',
 '홍성역사인물축제',
 '광천김토굴새우젓축제',
 '군포철쭉축제',
 '제21회 광릉숲축제',
 '제40회 정약용문화제',
 '10월 마토예술제',
 '제13회 노을동요제',
 '평택호 물빛축제',
 '제16회 평택뮤직페스티벌&전국밴드경연대회',
 '6월 마토예술제',
 '평택 원평나루 억새축제',
 '제63회 수원화성문화제',
 '2026 정조대왕 능행차 공동재현',
 '2026 수원화성 미디어아트',
 '슬도아트 미디어아트 전시 [슬도의 울림:바다가 전하는 디지털 호흡]',
 '슬도아트 전시 [나에게 가장 솔직하고 진심이었던 순간들]',
 '문화공장 방어진 [찰나의 안녕]',
 '2026 대덕물빛축제',
 '제29회 동춘당문화제',
 '제23회 광주 추억의 충장축제',
 '제4회 무등산 인문축제',
 '광주 국가유산 야행',
 '금남로 차 없는 거리 걷자잉',
 '제5회 광주 버스킹 월드컵',
 '정서진 해넘이 행사',
 '아라뱃길 카약축제',
 '장미꽃 필(feel)무렵',
 '희망달서 대축제',
 '중랑 북페스티벌',
 '겸재책거리축제',
 '용마폭포문화예술축제',
 '중랑 서울장미축제',
 '남한산성문화제',
 '광주왕실도자페스티벌',
 '제3회 광나루 해오름 축제',
 '2025 청춘대로',
 '2025 아차산 해맞이 축제',
 '클래식소풍',
 '2024년 제1회 광진생활문화예술축제',
 '2024 피크닉인나루',
 '2024 청춘대로',
 '광진가족 클래식 음악산책 지브리 콘서트',
 '2024 행복광진 힐링축제',
 '2024 제2회 광진가족 영화제',
 '2024 제1회 광진가족 영화제',
 '2024 광진가족페스티벌',
 '제6회 명품한강 장미축제',
 '2024 아차산 해맞이 축제',
 '광장동 주민한마당 광나루 해오름축제',
 '2023 제6회 능동 감마을 축제',
 '2023 행복나눔 구일 마을문화 축제',
 '제7회 자양뚝방길 가을음악회',
 '주민과 함께하는 제3회 이랴이랴 자신만만 축제',
 '자양4동 주민 소통한마당 축제',
 '제2회 숲나루 꿈의 축제',
 '제7회 구삼축제 한마당',
 '광진구민과 함께하는 심포니 콘서트',
 '제9회 긴고랑 한마음 축제',
 '2023 광진가족영화제',
 '광진구민과 함께하는 숲나루 콘서트',
 '제10회 느티마을 한마당 축제',
 '2023 광진가족영화제',
 '2023 군자 한마당축제',
 '제5회 명품한강 장미축제',
 '제1회 중곡3동 벚꽃축제',
 '제1회 중곡2동 긴고랑 왕벚꽃축제',
 '2026 아차산 해맞이 축제',
 '당진 삽교호 드론 라이트 쇼',
 '당진면천읍성축제',
 '순성왕매실&당진맥주축제',
 '순성 벚꽃축제',
 '왜목마을 해넘이·해돋이 소원제',
 '심훈상록문화제',
 '남이흥장군문화제',
 '기지시줄다리기축제',
 '당진합덕연꽃축제',
 '당진 댄스 페스티벌',
 '2025고령 대가야축제',
 '제27회 화순운주문화축제',
 '2026 화순 고인돌 가을꽃 축제',
 '제39회 화순적벽문화축제',
 '2026 화학산 고산 철쭉제',
 '제29회 백아산 철쭉제 및 6.25 희생자 위령제',
 '화순 남산공원 로컬힙 프로젝트',
 '제1회 동복 숲정이 봄꽃 축제',
 '2026 화순 봄꽃 축제',
 '미리미리 크리스마스',
 '꽃지 해넘이 행사',
 '연포 해맞이 행사',
 '백화산 해맞이 행사',
 '예당호 해맞이 행사 안내',
 '천안성환배축제',
 '입장거봉포도축제',
 '천안흥타령춤축제',
 '천안호두축제',
 '제20회 시흥갯골축제',
 '대전효문화뿌리축제',
 '2025년 제18회 정읍 구절초 꽃축제',
 '2025 정읍 물빛축제',
 '제58회 동학농민혁명기념제',
 '2025년 정읍 벚꽃축제',
 '순천 대학로 축제',
 '제2회 글로벌 콘텐츠 페스티벌 in 순천',
 '제12회 순천웃장 국밥축제',
 '역전 싱싱거리 페스타',
 '(가칭)열대야 탈출 올랑가',
 '2025 순천 비어페스타',
 '원츠(Wants) 순천',
 '오성한옥마을 오픈가든축제',
 '와일드&로컬푸드 축제',
 '대둔산 축제',
 '모악산 웰니스 축제',
 '신월랑 달빛 축제',
 '섬강축제',
 '반계리 은행나무축제',
 '2025 원주 댄싱카니발',
 '장미축제',
 '용수골꽃양귀비축제',
 '제27회 원주한지문화제',
 '치악산왕발걸음축제',
 '명량대첩축제',
 '진도군 보배섬 문화예술제',
 '2025 전주가맥축제',
 '2025 전주단오',
 '2025 전주비빔밥축제',
 '2025 전주독서대전',
 '양양 송이&연어축제',
 '양양문화제',
 '2025 포천 한탄강 가든페스타',
 '제20회 포천백운계곡 동장군 축제',
 '제19회 포천백운계곡 동장군 축제',
 '제27회 포천 산정호수 명성산 억새꽃 축제',
 '울산옹기축제',
 '청산도슬로걷기축제',
 '장보고수산물축제',
 '사과축제',
 '인삼한우축제',
 '맥주축제',
 '찰옥수수축제',
 '산나물축제',
 '제27회 UN평화축제',
 '2025 을사년 정월대보름 달맞이축제',
 '곡성심청어린이대축제',
 '제26회 하동야생차문화축제',
 '제25회 화개장터벚꽃축제',
 '하동왕의녹차참숭어축제',
 '악양대봉감축제',
 '회남재숲길걷기',
 '평사리황금들판허수아비전시',
 '인천원도사제낙섬축제',
 '미추홀미디어문화축제',
 '한성백제문화제',
 '석촌호수벚꽃축제',
 '2025 전주세계소리축제',
 '2025 전주국제한지산업대전',
 '제1회 양천가족 거리축제',
 '어울림 한마당 축제',
 '제6회 신정1동 마을축제',
 '2024 양천구 반려동물 문화축제',
 '제13회 양천마라톤',
 '제26회 전주국제영화제',
 '2025 전주 얼티밋 뮤직 페스티벌',
 'DMZ피스트레인 뮤직 페스티벌',
 '철원 DMZ 평화 꽃송이 축제',
 '신월6,신정3 한마음 문화축제',
 '나말모새미 축제',
 '제8회 해맞이마을축제',
 '제1회 오목공원 가을축제',
 '고운달 마을사랑 대잔치',
 '제4회 용왕산 달빛거리 축제',
 '목동로데오패션거리 문화축제',
 '걷고 싶은 거리 단풍 축제',
 '제4회 능골산 청소년 문화축제',
 '2024 파리공원문화축제',
 '2025 양천 비체나라 페스티벌',
 '제2회 양천가족 거리축제',
 '영주장날 농특산물대축제',
 '경북영주 풍기인삼축제',
 '영주 무섬외나무다리축제',
 '영주 시원(ONE)축제',
 '영주 소백산철쭉제',
 '월산면 용구산 들꽃축제',
 '무정면 은행나무 축제',
 '가로수사랑음악회',
 '창평전통음식축제',
 '고비산 산 벚꽃축제',
 '담양산타축제',
 '담양대나무축제',
 '2025 파리공원문화축제',
 '2019 송년콘서트 및 청소년페스티벌',
 '제13회 철원 화강 다슬기축제',
 '제8회 철원 한탄강 얼음트레킹',
 '제7회 신정1동 축제 마을소풍',
 '신월4동 어울림 한마당 축제',
 '저도 대문어축제',
 '초도성게축제',
 '오호항 도루묵 축제',
 '고성군민의 날 및 수성문화제',
 '고성통일명태축제',
 '제43회 설성문화제',
 '제26회 음성품바축제',
 '제5회 능골산 청소년 문화축제',
 '제9회 해맞이마을축제',
 '제4회 용왕산 달빛거리 축제',
 '고운달 마을사랑 대잔치',
 '제7회 행복나눔 마을 축제',
 '지지고 부치는 요리경연대회 ‘전설의 부침개 달인’',
 '신월6,신정3 한마음 문화축제',
 '갈산-호돌이 축제',
 '2025년 장수공원 달빛 축제',
 '목3동 등마루 축제',
 '오목공원 가을축제',
 '제4회 신정이 어울림 한마당',
 '웰컴백 은행정 한마음 나눔 축제',
 '제14회 방아다리 벚꽃축제',
 '서울숲 JAZZ페스티벌',
 '태조 이성계 축제',
 '세계민속춤 축제',
 '제51회신라문화제',
 '양구사과시래기축제',
 '양록제',
 '양구배꼽축제',
 '양구곰취축제',
 '두모포 페스티벌',
 '응봉산 개나리 축제',
 '응봉산 해맞이 축제',
 '제12회 대한민국와인축제',
 '여수향일암일출제',
 '찾아라, 여수의 맛 섬슐랭 페스타',
 '여수밤바다 불꽃축제',
 '여수동동북축제',
 '여수여자만갯벌노을체험행사',
 '거문도백도은빛바다체험행사',
 '여수거북선축제',
 '청년거리문화한마당',
 '여수영취산진달래체험행사',
 '2025 제주올레걷기축제',
 '2025 영천동해바라기축제',
 '제 64회 탐라문화제',
 '고흥 우주항공 축제',
 '제 31회 서귀포칠십리축제',
 '펠롱펠롱 빛 모드락',
 '2025 서귀포 크루즈 페스타',
 '제 21회 쇠소깍축제',
 '2025 두 발과 두 바퀴로 더 푸른 제주',
 '무브먼트 코리아 인 서귀포',
 '제 8회 하하페스티벌',
 '신시모도삼형제보물섬축제',
 ...]

In [5]:
len(name_list)

1300

In [6]:
name = pd.read_csv('festival_result_realistic.csv')
name.head()

     구미라면축제     방문객수
0    김천김밥축제   147000
1   임실N치즈축제  1187000
2  여주오곡나루축제    19000
3  강동선사문화축제   240000
4    목포항구축제   118000

In [7]:
df['방문객수'] = name['방문객수']

df.head()

,축제명,개최장소,축제시작일자,축제종료일자,축제내용,주관기관명,주최기관명,후원기관명,전화번호,홈페이지주소,관련정보,소재지도로명주소,소재지지번주소,위도,경도,데이터기준일자,제공기관코드,제공기관명,방문객수
0,구미라면축제,구미역 일원,2026-11-06,2026-11-08,이색라면 레스토랑 및 `갓 튀긴 라면` 팝업스토어 운영 등,경상북도 구미시,경상북도 구미시,NaN,054-480-2652,https://www.gumiramyun.com/,NaN,NaN,경상북도 구미시 원평동 124-23,36.129403,128.331413,2026-06-16,B551011,한국관광공사,147000.0
1,김천김밥축제,직지문화공원 및 사명대사공원 일원,2026-10-23,2026-10-25,김밥플레이리스트(축하공연)+꼬달이 돌잡이 등,경상북도 김천시,경상북도 김천시,NaN,053-965-0910,https://gimbapcity.kr/,NaN,경상북도 김천시 대항면 황악로 1189-52,경상북도 김천시 대항면 운수리 산44-1,36.103084,127.992908,2026-06-16,B551011,한국관광공사,1187000.0
2,임실N치즈축제,임실치즈테마파크+임실치즈마을+임실읍 일원,2026-10-08,2026-10-11,임실N치즈 쭉쭉늘려 내치즈+디저트 퐁뒤체험+국가대표 임실N치즈 대형 쌀피자,임실N치즈축제제전위원회,임실N치즈축제제전위원회,문화체육관광부+농림축산식품부+한국관광공사+전북특별자치도+전북특별자치도 임실군,063-643-3900,www.imsilfestival.com,NaN,전북특별자치도 임실군 성수면 도인2길 50,전북특별자치도 임실군 성수면 도인리 689,35.633102,127.301258,2026-06-16,B551011,한국관광공사,19000.0
3,여주오곡나루축제,여주 신륵사관광지 일원,2026-10-23,2026-10-25,여주쌀 가마솥 비빔밥+군고구마 기네스+여주 본두리 낙화놀이+여주 흔암리 쌍용거 줄다...,여주세종문화관광재단,경기도 여주시,NaN,031-881-9694,https://www.yjfestival.or.kr/,NaN,경기도 여주시 신륵사길 7,경기도 여주시 천송동 297-1,37.300017,127.656746,2026-06-16,B551011,한국관광공사,240000.0
4,강동선사문화축제,서울 암사동 유적,2026-10-16,2026-10-18,개폐막식+축하공연+개막 드론쇼+폐막 불꽃쇼+거리퍼레이드+강동선사 노래자랑+자치회관 ...,서울특별시 강동구,서울특별시 강동구,NaN,02-3425-5240,https://www.gdsunsa.com/,NaN,서울특별시 강동구 올림픽로 875 (암사동),서울특별시 강동구 암사동 139-2,37.559854,127.130832,2026-06-16,B551011,한국관광공사,118000.0

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1300 entries, 0 to 1299
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   축제명       1300 non-null   str
 1   개최장소      1300 non-null   str
 2   축제시작일자    1300 non-null   str
 3   축제종료일자    1300 non-null   str
 4   축제내용      1300 non-null   str
 5   주관기관명     1300 non-null   str
 6   주최기관명     1300 non-null   str
 7   후원기관명     597 non-null    str
 8   전화번호      1208 non-null   str
 9   홈페이지주소    813 non-null    str
 10  관련정보      146 non-null    str
 11  소재지도로명주소  1088 non-null   str
 12  소재지지번주소   1063 non-null   str
 13  위도        1072 non-null   float64
 14  경도        1072 non-null   float64
 15  데이터기준일자   1300 non-null   str
 16  제공기관코드    1300 non-null   str
 17  제공기관명     1300 non-null   str
 18  방문객수      1299 non-null   float64
dtypes: float64(3), str(16)
memory usage: 193.1 KB

In [9]:
df['축제시작일자'] = pd.to_datetime(df['축제시작일자'])
df['축제종료일자'] = pd.to_datetime(df['축제종료일자'])

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1300 entries, 0 to 1299
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   축제명       1300 non-null   str
 1   개최장소      1300 non-null   str
 2   축제시작일자    1300 non-null   datetime64[us]
 3   축제종료일자    1300 non-null   datetime64[us]
 4   축제내용      1300 non-null   str
 5   주관기관명     1300 non-null   str
 6   주최기관명     1300 non-null   str
 7   후원기관명     597 non-null    str
 8   전화번호      1208 non-null   str
 9   홈페이지주소    813 non-null    str
 10  관련정보      146 non-null    str
 11  소재지도로명주소  1088 non-null   str
 12  소재지지번주소   1063 non-null   str
 13  위도        1072 non-null   float64
 14  경도        1072 non-null   float64
 15  데이터기준일자   1300 non-null   str
 16  제공기관코드    1300 non-null   str
 17  제공기관명     1300 non-null   str
 18  방문객수      1299 non-null   float64
dtypes: datetime64[us](2), float64(3), str(14)
memory usage: 193.1 KB

In [11]:
df['행사기간'] = (df['축제종료일자'] - df['축제시작일자']).dt.days + 1

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1300 entries, 0 to 1299
Data columns (total 20 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   축제명       1300 non-null   str
 1   개최장소      1300 non-null   str
 2   축제시작일자    1300 non-null   datetime64[us]
 3   축제종료일자    1300 non-null   datetime64[us]
 4   축제내용      1300 non-null   str
 5   주관기관명     1300 non-null   str
 6   주최기관명     1300 non-null   str
 7   후원기관명     597 non-null    str
 8   전화번호      1208 non-null   str
 9   홈페이지주소    813 non-null    str
 10  관련정보      146 non-null    str
 11  소재지도로명주소  1088 non-null   str
 12  소재지지번주소   1063 non-null   str
 13  위도        1072 non-null   float64
 14  경도        1072 non-null   float64
 15  데이터기준일자   1300 non-null   str
 16  제공기관코드    1300 non-null   str
 17  제공기관명     1300 non-null   str
 18  방문객수      1299 non-null   float64
 19  행사기간      1300 non-null   int64
dtypes: datetime64[us](2), float64(3), int64(1), str(14)
memory usage: 203.3 KB

In [13]:
df.head()

,축제명,개최장소,축제시작일자,축제종료일자,축제내용,주관기관명,주최기관명,후원기관명,전화번호,홈페이지주소,관련정보,소재지도로명주소,소재지지번주소,위도,경도,데이터기준일자,제공기관코드,제공기관명,방문객수,행사기간
0,구미라면축제,구미역 일원,2026-11-06,2026-11-08,이색라면 레스토랑 및 `갓 튀긴 라면` 팝업스토어 운영 등,경상북도 구미시,경상북도 구미시,NaN,054-480-2652,https://www.gumiramyun.com/,NaN,NaN,경상북도 구미시 원평동 124-23,36.129403,128.331413,2026-06-16,B551011,한국관광공사,147000.0,3
1,김천김밥축제,직지문화공원 및 사명대사공원 일원,2026-10-23,2026-10-25,김밥플레이리스트(축하공연)+꼬달이 돌잡이 등,경상북도 김천시,경상북도 김천시,NaN,053-965-0910,https://gimbapcity.kr/,NaN,경상북도 김천시 대항면 황악로 1189-52,경상북도 김천시 대항면 운수리 산44-1,36.103084,127.992908,2026-06-16,B551011,한국관광공사,1187000.0,3
2,임실N치즈축제,임실치즈테마파크+임실치즈마을+임실읍 일원,2026-10-08,2026-10-11,임실N치즈 쭉쭉늘려 내치즈+디저트 퐁뒤체험+국가대표 임실N치즈 대형 쌀피자,임실N치즈축제제전위원회,임실N치즈축제제전위원회,문화체육관광부+농림축산식품부+한국관광공사+전북특별자치도+전북특별자치도 임실군,063-643-3900,www.imsilfestival.com,NaN,전북특별자치도 임실군 성수면 도인2길 50,전북특별자치도 임실군 성수면 도인리 689,35.633102,127.301258,2026-06-16,B551011,한국관광공사,19000.0,4
3,여주오곡나루축제,여주 신륵사관광지 일원,2026-10-23,2026-10-25,여주쌀 가마솥 비빔밥+군고구마 기네스+여주 본두리 낙화놀이+여주 흔암리 쌍용거 줄다...,여주세종문화관광재단,경기도 여주시,NaN,031-881-9694,https://www.yjfestival.or.kr/,NaN,경기도 여주시 신륵사길 7,경기도 여주시 천송동 297-1,37.300017,127.656746,2026-06-16,B551011,한국관광공사,240000.0,3
4,강동선사문화축제,서울 암사동 유적,2026-10-16,2026-10-18,개폐막식+축하공연+개막 드론쇼+폐막 불꽃쇼+거리퍼레이드+강동선사 노래자랑+자치회관 ...,서울특별시 강동구,서울특별시 강동구,NaN,02-3425-5240,https://www.gdsunsa.com/,NaN,서울특별시 강동구 올림픽로 875 (암사동),서울특별시 강동구 암사동 139-2,37.559854,127.130832,2026-06-16,B551011,한국관광공사,118000.0,3

In [14]:
df["광역시도"] = df["소재지지번주소"].str.split().str[0]

In [15]:
df.head()

,축제명,개최장소,축제시작일자,축제종료일자,축제내용,주관기관명,주최기관명,후원기관명,전화번호,홈페이지주소,...,소재지도로명주소,소재지지번주소,위도,경도,데이터기준일자,제공기관코드,제공기관명,방문객수,행사기간,광역시도
0,구미라면축제,구미역 일원,2026-11-06,2026-11-08,이색라면 레스토랑 및 `갓 튀긴 라면` 팝업스토어 운영 등,경상북도 구미시,경상북도 구미시,NaN,054-480-2652,https://www.gumiramyun.com/,...,NaN,경상북도 구미시 원평동 124-23,36.129403,128.331413,2026-06-16,B551011,한국관광공사,147000.0,3,경상북도
1,김천김밥축제,직지문화공원 및 사명대사공원 일원,2026-10-23,2026-10-25,김밥플레이리스트(축하공연)+꼬달이 돌잡이 등,경상북도 김천시,경상북도 김천시,NaN,053-965-0910,https://gimbapcity.kr/,...,경상북도 김천시 대항면 황악로 1189-52,경상북도 김천시 대항면 운수리 산44-1,36.103084,127.992908,2026-06-16,B551011,한국관광공사,1187000.0,3,경상북도
2,임실N치즈축제,임실치즈테마파크+임실치즈마을+임실읍 일원,2026-10-08,2026-10-11,임실N치즈 쭉쭉늘려 내치즈+디저트 퐁뒤체험+국가대표 임실N치즈 대형 쌀피자,임실N치즈축제제전위원회,임실N치즈축제제전위원회,문화체육관광부+농림축산식품부+한국관광공사+전북특별자치도+전북특별자치도 임실군,063-643-3900,www.imsilfestival.com,...,전북특별자치도 임실군 성수면 도인2길 50,전북특별자치도 임실군 성수면 도인리 689,35.633102,127.301258,2026-06-16,B551011,한국관광공사,19000.0,4,전북특별자치도
3,여주오곡나루축제,여주 신륵사관광지 일원,2026-10-23,2026-10-25,여주쌀 가마솥 비빔밥+군고구마 기네스+여주 본두리 낙화놀이+여주 흔암리 쌍용거 줄다...,여주세종문화관광재단,경기도 여주시,NaN,031-881-9694,https://www.yjfestival.or.kr/,...,경기도 여주시 신륵사길 7,경기도 여주시 천송동 297-1,37.300017,127.656746,2026-06-16,B551011,한국관광공사,240000.0,3,경기도
4,강동선사문화축제,서울 암사동 유적,2026-10-16,2026-10-18,개폐막식+축하공연+개막 드론쇼+폐막 불꽃쇼+거리퍼레이드+강동선사 노래자랑+자치회관 ...,서울특별시 강동구,서울특별시 강동구,NaN,02-3425-5240,https://www.gdsunsa.com/,...,서울특별시 강동구 올림픽로 875 (암사동),서울특별시 강동구 암사동 139-2,37.559854,127.130832,2026-06-16,B551011,한국관광공사,118000.0,3,서울특별시

In [16]:
df.groupby("광역시도")["방문객수"].sum()

광역시도
강원도          627000.0
강원특별자치도    17969000.0
경기도        51022000.0
경상남도       18388500.0
경상북도       13939000.0
광주광역시       6519000.0
대구광역시      13041500.0
대전광역시       5772000.0
부산광역시       7433500.0
서울시          427000.0
서울특별시      21623000.0
세종특별자치시     1811500.0
울산광역시       6645500.0
인천광역시       6964000.0
전라남도       20870500.0
전북특별자치도    17798000.0
제주특별자치도     2075000.0
충남            38500.0
충청남도       23602000.0
충청북도        7873000.0
Name: 방문객수, dtype: float64

In [17]:
replace_dict = {
    "서울특별시": "서울",
    "서울시": "서울",
    "경기도": "경기",
    "강원도": "강원",
    "강원특별자치도": "강원",
    "경상북도": "경북",
    "경상남도": "경남",
    "전라북도": "전북",
    "전북특별자치도": "전북",
    "전라남도": "전남",
    "충청북도": "충북",
    "충청남도": "충남",
    "충남": "충남",
    "부산광역시": "부산",
    "대구광역시": "대구",
    "인천광역시": "인천",
    "광주광역시": "광주",
    "대전광역시": "대전",
    "울산광역시": "울산",
    "세종특별자치시": "세종",
    "제주특별자치도": "제주"
}

df["광역시도"] = df["광역시도"].replace(replace_dict)

df.head()

,축제명,개최장소,축제시작일자,축제종료일자,축제내용,주관기관명,주최기관명,후원기관명,전화번호,홈페이지주소,...,소재지도로명주소,소재지지번주소,위도,경도,데이터기준일자,제공기관코드,제공기관명,방문객수,행사기간,광역시도
0,구미라면축제,구미역 일원,2026-11-06,2026-11-08,이색라면 레스토랑 및 `갓 튀긴 라면` 팝업스토어 운영 등,경상북도 구미시,경상북도 구미시,NaN,054-480-2652,https://www.gumiramyun.com/,...,NaN,경상북도 구미시 원평동 124-23,36.129403,128.331413,2026-06-16,B551011,한국관광공사,147000.0,3,경북
1,김천김밥축제,직지문화공원 및 사명대사공원 일원,2026-10-23,2026-10-25,김밥플레이리스트(축하공연)+꼬달이 돌잡이 등,경상북도 김천시,경상북도 김천시,NaN,053-965-0910,https://gimbapcity.kr/,...,경상북도 김천시 대항면 황악로 1189-52,경상북도 김천시 대항면 운수리 산44-1,36.103084,127.992908,2026-06-16,B551011,한국관광공사,1187000.0,3,경북
2,임실N치즈축제,임실치즈테마파크+임실치즈마을+임실읍 일원,2026-10-08,2026-10-11,임실N치즈 쭉쭉늘려 내치즈+디저트 퐁뒤체험+국가대표 임실N치즈 대형 쌀피자,임실N치즈축제제전위원회,임실N치즈축제제전위원회,문화체육관광부+농림축산식품부+한국관광공사+전북특별자치도+전북특별자치도 임실군,063-643-3900,www.imsilfestival.com,...,전북특별자치도 임실군 성수면 도인2길 50,전북특별자치도 임실군 성수면 도인리 689,35.633102,127.301258,2026-06-16,B551011,한국관광공사,19000.0,4,전북
3,여주오곡나루축제,여주 신륵사관광지 일원,2026-10-23,2026-10-25,여주쌀 가마솥 비빔밥+군고구마 기네스+여주 본두리 낙화놀이+여주 흔암리 쌍용거 줄다...,여주세종문화관광재단,경기도 여주시,NaN,031-881-9694,https://www.yjfestival.or.kr/,...,경기도 여주시 신륵사길 7,경기도 여주시 천송동 297-1,37.300017,127.656746,2026-06-16,B551011,한국관광공사,240000.0,3,경기
4,강동선사문화축제,서울 암사동 유적,2026-10-16,2026-10-18,개폐막식+축하공연+개막 드론쇼+폐막 불꽃쇼+거리퍼레이드+강동선사 노래자랑+자치회관 ...,서울특별시 강동구,서울특별시 강동구,NaN,02-3425-5240,https://www.gdsunsa.com/,...,서울특별시 강동구 올림픽로 875 (암사동),서울특별시 강동구 암사동 139-2,37.559854,127.130832,2026-06-16,B551011,한국관광공사,118000.0,3,서울

In [18]:
df.isnull().sum()

축제명            0
개최장소           0
축제시작일자         0
축제종료일자         0
축제내용           0
주관기관명          0
주최기관명          0
후원기관명        703
전화번호          92
홈페이지주소       487
관련정보        1154
소재지도로명주소     212
소재지지번주소      237
위도           228
경도           228
데이터기준일자        0
제공기관코드         0
제공기관명          0
방문객수           1
행사기간           0
광역시도         237
dtype: int64

In [19]:
df.head()

,축제명,개최장소,축제시작일자,축제종료일자,축제내용,주관기관명,주최기관명,후원기관명,전화번호,홈페이지주소,...,소재지도로명주소,소재지지번주소,위도,경도,데이터기준일자,제공기관코드,제공기관명,방문객수,행사기간,광역시도
0,구미라면축제,구미역 일원,2026-11-06,2026-11-08,이색라면 레스토랑 및 `갓 튀긴 라면` 팝업스토어 운영 등,경상북도 구미시,경상북도 구미시,NaN,054-480-2652,https://www.gumiramyun.com/,...,NaN,경상북도 구미시 원평동 124-23,36.129403,128.331413,2026-06-16,B551011,한국관광공사,147000.0,3,경북
1,김천김밥축제,직지문화공원 및 사명대사공원 일원,2026-10-23,2026-10-25,김밥플레이리스트(축하공연)+꼬달이 돌잡이 등,경상북도 김천시,경상북도 김천시,NaN,053-965-0910,https://gimbapcity.kr/,...,경상북도 김천시 대항면 황악로 1189-52,경상북도 김천시 대항면 운수리 산44-1,36.103084,127.992908,2026-06-16,B551011,한국관광공사,1187000.0,3,경북
2,임실N치즈축제,임실치즈테마파크+임실치즈마을+임실읍 일원,2026-10-08,2026-10-11,임실N치즈 쭉쭉늘려 내치즈+디저트 퐁뒤체험+국가대표 임실N치즈 대형 쌀피자,임실N치즈축제제전위원회,임실N치즈축제제전위원회,문화체육관광부+농림축산식품부+한국관광공사+전북특별자치도+전북특별자치도 임실군,063-643-3900,www.imsilfestival.com,...,전북특별자치도 임실군 성수면 도인2길 50,전북특별자치도 임실군 성수면 도인리 689,35.633102,127.301258,2026-06-16,B551011,한국관광공사,19000.0,4,전북
3,여주오곡나루축제,여주 신륵사관광지 일원,2026-10-23,2026-10-25,여주쌀 가마솥 비빔밥+군고구마 기네스+여주 본두리 낙화놀이+여주 흔암리 쌍용거 줄다...,여주세종문화관광재단,경기도 여주시,NaN,031-881-9694,https://www.yjfestival.or.kr/,...,경기도 여주시 신륵사길 7,경기도 여주시 천송동 297-1,37.300017,127.656746,2026-06-16,B551011,한국관광공사,240000.0,3,경기
4,강동선사문화축제,서울 암사동 유적,2026-10-16,2026-10-18,개폐막식+축하공연+개막 드론쇼+폐막 불꽃쇼+거리퍼레이드+강동선사 노래자랑+자치회관 ...,서울특별시 강동구,서울특별시 강동구,NaN,02-3425-5240,https://www.gdsunsa.com/,...,서울특별시 강동구 올림픽로 875 (암사동),서울특별시 강동구 암사동 139-2,37.559854,127.130832,2026-06-16,B551011,한국관광공사,118000.0,3,서울

In [20]:
bus_df = pd.read_csv('국토교통부_전국 버스정류장 위치정보_20251031.csv', encoding='cp949')

bus_df.head()

,정류장번호,정류장명,위도,경도,정보수집일,모바일단축번호,도시코드,도시명,관리도시명
0,ADB354000001,길안정류장,36.458658,128.891228,2025-10-31,540001.0,37040,경상북도 안동시,안동BIS
1,ADB354000002,고란.계명산휴양림입구,36.397708,128.924029,2025-10-31,540002.0,37040,경상북도 안동시,안동BIS
2,ADB354000003,금곡리,36.397504,128.926821,2025-10-31,540003.0,37040,경상북도 안동시,안동BIS
3,ADB354000004,금소리1,36.509449,128.849671,2025-10-31,540004.0,37040,경상북도 안동시,안동BIS
4,ADB354000005,금소리5,36.503629,128.854783,2025-10-31,540005.0,37040,경상북도 안동시,안동BIS

In [21]:
bus_df["광역시도"] = bus_df["도시명"].str.split().str[0]
bus_df.head()

,정류장번호,정류장명,위도,경도,정보수집일,모바일단축번호,도시코드,도시명,관리도시명,광역시도
0,ADB354000001,길안정류장,36.458658,128.891228,2025-10-31,540001.0,37040,경상북도 안동시,안동BIS,경상북도
1,ADB354000002,고란.계명산휴양림입구,36.397708,128.924029,2025-10-31,540002.0,37040,경상북도 안동시,안동BIS,경상북도
2,ADB354000003,금곡리,36.397504,128.926821,2025-10-31,540003.0,37040,경상북도 안동시,안동BIS,경상북도
3,ADB354000004,금소리1,36.509449,128.849671,2025-10-31,540004.0,37040,경상북도 안동시,안동BIS,경상북도
4,ADB354000005,금소리5,36.503629,128.854783,2025-10-31,540005.0,37040,경상북도 안동시,안동BIS,경상북도

In [22]:
replace_dict = {
    "서울특별시": "서울",
    "서울시": "서울",
    "경기도": "경기",
    "강원도": "강원",
    "강원특별자치도": "강원",
    "경상북도": "경북",
    "경상남도": "경남",
    "전라북도": "전북",
    "전북특별자치도": "전북",
    "전라남도": "전남",
    "충청북도": "충북",
    "충청남도": "충남",
    "충남": "충남",
    "부산광역시": "부산",
    "대구광역시": "대구",
    "인천광역시": "인천",
    "광주광역시": "광주",
    "대전광역시": "대전",
    "울산광역시": "울산",
    "세종특별자치시": "세종",
    "제주특별자치도": "제주"
}

bus_df["광역시도"] = bus_df["광역시도"].replace(replace_dict)

bus_df.head()

,정류장번호,정류장명,위도,경도,정보수집일,모바일단축번호,도시코드,도시명,관리도시명,광역시도
0,ADB354000001,길안정류장,36.458658,128.891228,2025-10-31,540001.0,37040,경상북도 안동시,안동BIS,경북
1,ADB354000002,고란.계명산휴양림입구,36.397708,128.924029,2025-10-31,540002.0,37040,경상북도 안동시,안동BIS,경북
2,ADB354000003,금곡리,36.397504,128.926821,2025-10-31,540003.0,37040,경상북도 안동시,안동BIS,경북
3,ADB354000004,금소리1,36.509449,128.849671,2025-10-31,540004.0,37040,경상북도 안동시,안동BIS,경북
4,ADB354000005,금소리5,36.503629,128.854783,2025-10-31,540005.0,37040,경상북도 안동시,안동BIS,경북

In [23]:
bus_count = bus_df['광역시도'].value_counts().to_dict()

In [24]:
df['버스정류장수'] = df['광역시도'].map(bus_count)

In [25]:
df.head()

,축제명,개최장소,축제시작일자,축제종료일자,축제내용,주관기관명,주최기관명,후원기관명,전화번호,홈페이지주소,...,소재지지번주소,위도,경도,데이터기준일자,제공기관코드,제공기관명,방문객수,행사기간,광역시도,버스정류장수
0,구미라면축제,구미역 일원,2026-11-06,2026-11-08,이색라면 레스토랑 및 `갓 튀긴 라면` 팝업스토어 운영 등,경상북도 구미시,경상북도 구미시,NaN,054-480-2652,https://www.gumiramyun.com/,...,경상북도 구미시 원평동 124-23,36.129403,128.331413,2026-06-16,B551011,한국관광공사,147000.0,3,경북,29735.0
1,김천김밥축제,직지문화공원 및 사명대사공원 일원,2026-10-23,2026-10-25,김밥플레이리스트(축하공연)+꼬달이 돌잡이 등,경상북도 김천시,경상북도 김천시,NaN,053-965-0910,https://gimbapcity.kr/,...,경상북도 김천시 대항면 운수리 산44-1,36.103084,127.992908,2026-06-16,B551011,한국관광공사,1187000.0,3,경북,29735.0
2,임실N치즈축제,임실치즈테마파크+임실치즈마을+임실읍 일원,2026-10-08,2026-10-11,임실N치즈 쭉쭉늘려 내치즈+디저트 퐁뒤체험+국가대표 임실N치즈 대형 쌀피자,임실N치즈축제제전위원회,임실N치즈축제제전위원회,문화체육관광부+농림축산식품부+한국관광공사+전북특별자치도+전북특별자치도 임실군,063-643-3900,www.imsilfestival.com,...,전북특별자치도 임실군 성수면 도인리 689,35.633102,127.301258,2026-06-16,B551011,한국관광공사,19000.0,4,전북,13180.0
3,여주오곡나루축제,여주 신륵사관광지 일원,2026-10-23,2026-10-25,여주쌀 가마솥 비빔밥+군고구마 기네스+여주 본두리 낙화놀이+여주 흔암리 쌍용거 줄다...,여주세종문화관광재단,경기도 여주시,NaN,031-881-9694,https://www.yjfestival.or.kr/,...,경기도 여주시 천송동 297-1,37.300017,127.656746,2026-06-16,B551011,한국관광공사,240000.0,3,경기,38089.0
4,강동선사문화축제,서울 암사동 유적,2026-10-16,2026-10-18,개폐막식+축하공연+개막 드론쇼+폐막 불꽃쇼+거리퍼레이드+강동선사 노래자랑+자치회관 ...,서울특별시 강동구,서울특별시 강동구,NaN,02-3425-5240,https://www.gdsunsa.com/,...,서울특별시 강동구 암사동 139-2,37.559854,127.130832,2026-06-16,B551011,한국관광공사,118000.0,3,서울,16980.0

In [26]:
subway_df = pd.read_csv('전체_도시철도역사정보_20260630.csv')
subway_df.head()

,역번호,역사명,노선번호,노선명,영문역사명,한자역사명,환승역구분,환승노선번호,환승노선명,역위도,역경도,운영기관명,역사도로명주소,역사전화번호,데이터기준일자
0,D004,신사,I11D1,신분당선,Sinsa,新沙,도시철도 환승역,I11D1,수도권 광역철도 신분당선,37.516125,127.019761,경기도 신분당선,서울특별시 강남구 강남대로 620-2,02) 810-5870,2026-06-18
1,D005,논현,I11D1,신분당선,Nonhyeon,論峴,도시철도 환승역,I11D1,수도권 광역철도 신분당선,37.511115,127.021366,경기도 신분당선,서울특별시 강남구 강남대로 492-2,02) 810-5860,2026-06-18
2,D006,신논현,I11D1,신분당선,Sinnonhyeon,新論峴,도시철도 환승역,I11D1,수도권 광역철도 신분당선,37.504555,127.024531,경기도 신분당선,서울특별시 강남구 강남대로 302-2,02) 810-5850,2026-06-18
3,D007,강남,I11D1,신분당선,Gangnam,江南,도시철도 환승역,I11D1,수도권 광역철도 신분당선,37.497385,127.027879,경기도 신분당선,서울특별시 강남구 강남대로 지하 396,02) 810-5840,2026-06-18
4,D008,양재(서초구청),I11D1,신분당선,Yangjae(Secho-gu Office),良才(瑞草區廳),도시철도 환승역,I11D1,수도권 광역철도 신분당선,37.484454,127.034099,경기도 신분당선,서울시 서초구 남부순환로 지하 2585,02) 810-5830,2026-06-18

In [27]:
subway_df["광역시도"] = subway_df["역사도로명주소"].str.split().str[0]
subway_df.head()

,역번호,역사명,노선번호,노선명,영문역사명,한자역사명,환승역구분,환승노선번호,환승노선명,역위도,역경도,운영기관명,역사도로명주소,역사전화번호,데이터기준일자,광역시도
0,D004,신사,I11D1,신분당선,Sinsa,新沙,도시철도 환승역,I11D1,수도권 광역철도 신분당선,37.516125,127.019761,경기도 신분당선,서울특별시 강남구 강남대로 620-2,02) 810-5870,2026-06-18,서울특별시
1,D005,논현,I11D1,신분당선,Nonhyeon,論峴,도시철도 환승역,I11D1,수도권 광역철도 신분당선,37.511115,127.021366,경기도 신분당선,서울특별시 강남구 강남대로 492-2,02) 810-5860,2026-06-18,서울특별시
2,D006,신논현,I11D1,신분당선,Sinnonhyeon,新論峴,도시철도 환승역,I11D1,수도권 광역철도 신분당선,37.504555,127.024531,경기도 신분당선,서울특별시 강남구 강남대로 302-2,02) 810-5850,2026-06-18,서울특별시
3,D007,강남,I11D1,신분당선,Gangnam,江南,도시철도 환승역,I11D1,수도권 광역철도 신분당선,37.497385,127.027879,경기도 신분당선,서울특별시 강남구 강남대로 지하 396,02) 810-5840,2026-06-18,서울특별시
4,D008,양재(서초구청),I11D1,신분당선,Yangjae(Secho-gu Office),良才(瑞草區廳),도시철도 환승역,I11D1,수도권 광역철도 신분당선,37.484454,127.034099,경기도 신분당선,서울시 서초구 남부순환로 지하 2585,02) 810-5830,2026-06-18,서울시

In [28]:
subway_regions = {
    '서울', '부산', '대구', '인천',
    '광주', '대전', '울산',
    '경기', '충남', '경남'
}

df['지하철유무'] = df['광역시도'].isin(subway_regions).map({True: 'Y', False: 'N'})

In [29]:
df.head()

,축제명,개최장소,축제시작일자,축제종료일자,축제내용,주관기관명,주최기관명,후원기관명,전화번호,홈페이지주소,...,위도,경도,데이터기준일자,제공기관코드,제공기관명,방문객수,행사기간,광역시도,버스정류장수,지하철유무
0,구미라면축제,구미역 일원,2026-11-06,2026-11-08,이색라면 레스토랑 및 `갓 튀긴 라면` 팝업스토어 운영 등,경상북도 구미시,경상북도 구미시,NaN,054-480-2652,https://www.gumiramyun.com/,...,36.129403,128.331413,2026-06-16,B551011,한국관광공사,147000.0,3,경북,29735.0,N
1,김천김밥축제,직지문화공원 및 사명대사공원 일원,2026-10-23,2026-10-25,김밥플레이리스트(축하공연)+꼬달이 돌잡이 등,경상북도 김천시,경상북도 김천시,NaN,053-965-0910,https://gimbapcity.kr/,...,36.103084,127.992908,2026-06-16,B551011,한국관광공사,1187000.0,3,경북,29735.0,N
2,임실N치즈축제,임실치즈테마파크+임실치즈마을+임실읍 일원,2026-10-08,2026-10-11,임실N치즈 쭉쭉늘려 내치즈+디저트 퐁뒤체험+국가대표 임실N치즈 대형 쌀피자,임실N치즈축제제전위원회,임실N치즈축제제전위원회,문화체육관광부+농림축산식품부+한국관광공사+전북특별자치도+전북특별자치도 임실군,063-643-3900,www.imsilfestival.com,...,35.633102,127.301258,2026-06-16,B551011,한국관광공사,19000.0,4,전북,13180.0,N
3,여주오곡나루축제,여주 신륵사관광지 일원,2026-10-23,2026-10-25,여주쌀 가마솥 비빔밥+군고구마 기네스+여주 본두리 낙화놀이+여주 흔암리 쌍용거 줄다...,여주세종문화관광재단,경기도 여주시,NaN,031-881-9694,https://www.yjfestival.or.kr/,...,37.300017,127.656746,2026-06-16,B551011,한국관광공사,240000.0,3,경기,38089.0,Y
4,강동선사문화축제,서울 암사동 유적,2026-10-16,2026-10-18,개폐막식+축하공연+개막 드론쇼+폐막 불꽃쇼+거리퍼레이드+강동선사 노래자랑+자치회관 ...,서울특별시 강동구,서울특별시 강동구,NaN,02-3425-5240,https://www.gdsunsa.com/,...,37.559854,127.130832,2026-06-16,B551011,한국관광공사,118000.0,3,서울,16980.0,Y

In [31]:
df.to_csv('전국문화축제정보정리.csv', index=False, encoding='utf-8-sig')

In [5]:
import pandas as pd
df_2 = pd.read_csv('data/전국문화축제정보정리.csv')
df_2.head()

,축제명,개최장소,축제시작일자,축제종료일자,축제내용,주관기관명,주최기관명,후원기관명,전화번호,홈페이지주소,...,위도,경도,데이터기준일자,제공기관코드,제공기관명,방문객수,행사기간,광역시도,버스정류장수,지하철유무
0,구미라면축제,구미역 일원,2026-11-06,2026-11-08,이색라면 레스토랑 및 `갓 튀긴 라면` 팝업스토어 운영 등,경상북도 구미시,경상북도 구미시,NaN,054-480-2652,https://www.gumiramyun.com/,...,36.129403,128.331413,2026-06-16,B551011,한국관광공사,147000.0,3,경북,29735.0,N
1,김천김밥축제,직지문화공원 및 사명대사공원 일원,2026-10-23,2026-10-25,김밥플레이리스트(축하공연)+꼬달이 돌잡이 등,경상북도 김천시,경상북도 김천시,NaN,053-965-0910,https://gimbapcity.kr/,...,36.103084,127.992908,2026-06-16,B551011,한국관광공사,1187000.0,3,경북,29735.0,N
2,임실N치즈축제,임실치즈테마파크+임실치즈마을+임실읍 일원,2026-10-08,2026-10-11,임실N치즈 쭉쭉늘려 내치즈+디저트 퐁뒤체험+국가대표 임실N치즈 대형 쌀피자,임실N치즈축제제전위원회,임실N치즈축제제전위원회,문화체육관광부+농림축산식품부+한국관광공사+전북특별자치도+전북특별자치도 임실군,063-643-3900,www.imsilfestival.com,...,35.633102,127.301258,2026-06-16,B551011,한국관광공사,19000.0,4,전북,13180.0,N
3,여주오곡나루축제,여주 신륵사관광지 일원,2026-10-23,2026-10-25,여주쌀 가마솥 비빔밥+군고구마 기네스+여주 본두리 낙화놀이+여주 흔암리 쌍용거 줄다...,여주세종문화관광재단,경기도 여주시,NaN,031-881-9694,https://www.yjfestival.or.kr/,...,37.300017,127.656746,2026-06-16,B551011,한국관광공사,240000.0,3,경기,38089.0,Y
4,강동선사문화축제,서울 암사동 유적,2026-10-16,2026-10-18,개폐막식+축하공연+개막 드론쇼+폐막 불꽃쇼+거리퍼레이드+강동선사 노래자랑+자치회관 ...,서울특별시 강동구,서울특별시 강동구,NaN,02-3425-5240,https://www.gdsunsa.com/,...,37.559854,127.130832,2026-06-16,B551011,한국관광공사,118000.0,3,서울,16980.0,Y

In [6]:
# df_2['예측방문객수'] = df_2['방문객수']

df_2.loc[
    df_2['버스정류장수'] > 20000,
    '방문객수'
] *= 1.2

df_2.loc[
    df_2['홈페이지주소'] == 1,
    '방문객수'
] *= 1.1

In [7]:
df_2

,축제명,개최장소,축제시작일자,축제종료일자,축제내용,주관기관명,주최기관명,후원기관명,전화번호,홈페이지주소,...,위도,경도,데이터기준일자,제공기관코드,제공기관명,방문객수,행사기간,광역시도,버스정류장수,지하철유무
0,구미라면축제,구미역 일원,2026-11-06,2026-11-08,이색라면 레스토랑 및 `갓 튀긴 라면` 팝업스토어 운영 등,경상북도 구미시,경상북도 구미시,NaN,054-480-2652,https://www.gumiramyun.com/,...,36.129403,128.331413,2026-06-16,B551011,한국관광공사,176400.0,3,경북,29735.0,N
1,김천김밥축제,직지문화공원 및 사명대사공원 일원,2026-10-23,2026-10-25,김밥플레이리스트(축하공연)+꼬달이 돌잡이 등,경상북도 김천시,경상북도 김천시,NaN,053-965-0910,https://gimbapcity.kr/,...,36.103084,127.992908,2026-06-16,B551011,한국관광공사,1424400.0,3,경북,29735.0,N
2,임실N치즈축제,임실치즈테마파크+임실치즈마을+임실읍 일원,2026-10-08,2026-10-11,임실N치즈 쭉쭉늘려 내치즈+디저트 퐁뒤체험+국가대표 임실N치즈 대형 쌀피자,임실N치즈축제제전위원회,임실N치즈축제제전위원회,문화체육관광부+농림축산식품부+한국관광공사+전북특별자치도+전북특별자치도 임실군,063-643-3900,www.imsilfestival.com,...,35.633102,127.301258,2026-06-16,B551011,한국관광공사,19000.0,4,전북,13180.0,N
3,여주오곡나루축제,여주 신륵사관광지 일원,2026-10-23,2026-10-25,여주쌀 가마솥 비빔밥+군고구마 기네스+여주 본두리 낙화놀이+여주 흔암리 쌍용거 줄다...,여주세종문화관광재단,경기도 여주시,NaN,031-881-9694,https://www.yjfestival.or.kr/,...,37.300017,127.656746,2026-06-16,B551011,한국관광공사,288000.0,3,경기,38089.0,Y
4,강동선사문화축제,서울 암사동 유적,2026-10-16,2026-10-18,개폐막식+축하공연+개막 드론쇼+폐막 불꽃쇼+거리퍼레이드+강동선사 노래자랑+자치회관 ...,서울특별시 강동구,서울특별시 강동구,NaN,02-3425-5240,https://www.gdsunsa.com/,...,37.559854,127.130832,2026-06-16,B551011,한국관광공사,118000.0,3,서울,16980.0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1295,제68회 백제문화제,금강신관공원,2022-10-01,2022-10-10,웅진성퍼레이드+체험마당+무대공연+농특산품전시 및 판매,백제문화선양위원회,백제문화제추진위원회,NaN,041-840-8112,https://www.baekje.org/kor/,...,36.478351,127.120424,2022-11-21,4500000,충청남도 공주시,172800.0,10,충남,24342.0,Y
1296,마곡사 신록축제,사곡면 운암리 마곡사일원,2022-05-07,2022-05-08,전시 운영+백범명상길 걷기+마곡사 보물찾기 등,마곡사신록축제추진위원회,공주시,NaN,041-840-2056,NaN,...,36.557406,127.011603,2022-11-21,4500000,충청남도 공주시,0.0,2,충남,24342.0,Y
1297,불갑산상사화축제,불갑사 관광지,2025-09-26,2025-10-05,문화축제,영광 불갑산상사화축제 집행위원회,영광 불갑산상사화축제 추진위원회,전라남도 영광군+영광군의회+한빛원자력본부,061-350-5269,http://상사화축제.com,...,35.199675,126.550048,2025-11-28,5890000,전남광주통합특별시 영광군,196000.0,10,전남,18483.0,N
1298,법성포단오제,법성포 뉴타운 일대,2025-05-29,2025-06-01,문화축제,(사)법성포단오제보존회,(사)법성포단오제보존회,전라남도 영광군+영광군의회+한빛원자력본부,061-356-4331,http://bspdanoje.co.kr,...,35.362652,126.435938,2025-11-28,5890000,전남광주통합특별시 영광군,40500.0,4,전남,18483.0,N
1299,제33회 성산일출축제,세계자연유산 성산일출봉 일원,2025-12-31,2026-01-01,올해의 끝과 새해의 시작은 성산일출축제에서 한 해를 마무리하고 새해를 맞이하며 유네...,성산일출축제위원회,제주특별자치도,NaN,NaN,https://www.sunrisefestival.kr/,...,33.464887,126.934279,2025-12-22,6500000,제주특별자치도,NaN,2,NaN,NaN,N

In [8]:
df_2.to_csv('전국문화축제정보정리2.csv', index=False, encoding='utf-8-sig')

In [20]:
import pandas as pd
bus_df = pd.read_csv('data/전국문화축제정보정리.csv')
bus_df.head()

,축제명,개최장소,축제시작일자,축제종료일자,축제내용,주관기관명,주최기관명,후원기관명,전화번호,홈페이지주소,...,위도,경도,데이터기준일자,제공기관코드,제공기관명,방문객수,행사기간,광역시도,버스정류장수,지하철유무
0,구미라면축제,구미역 일원,2026-11-06,2026-11-08,이색라면 레스토랑 및 `갓 튀긴 라면` 팝업스토어 운영 등,경상북도 구미시,경상북도 구미시,NaN,054-480-2652,https://www.gumiramyun.com/,...,36.129403,128.331413,2026-06-16,B551011,한국관광공사,147000.0,3,경북,29735.0,N
1,김천김밥축제,직지문화공원 및 사명대사공원 일원,2026-10-23,2026-10-25,김밥플레이리스트(축하공연)+꼬달이 돌잡이 등,경상북도 김천시,경상북도 김천시,NaN,053-965-0910,https://gimbapcity.kr/,...,36.103084,127.992908,2026-06-16,B551011,한국관광공사,1187000.0,3,경북,29735.0,N
2,임실N치즈축제,임실치즈테마파크+임실치즈마을+임실읍 일원,2026-10-08,2026-10-11,임실N치즈 쭉쭉늘려 내치즈+디저트 퐁뒤체험+국가대표 임실N치즈 대형 쌀피자,임실N치즈축제제전위원회,임실N치즈축제제전위원회,문화체육관광부+농림축산식품부+한국관광공사+전북특별자치도+전북특별자치도 임실군,063-643-3900,www.imsilfestival.com,...,35.633102,127.301258,2026-06-16,B551011,한국관광공사,19000.0,4,전북,13180.0,N
3,여주오곡나루축제,여주 신륵사관광지 일원,2026-10-23,2026-10-25,여주쌀 가마솥 비빔밥+군고구마 기네스+여주 본두리 낙화놀이+여주 흔암리 쌍용거 줄다...,여주세종문화관광재단,경기도 여주시,NaN,031-881-9694,https://www.yjfestival.or.kr/,...,37.300017,127.656746,2026-06-16,B551011,한국관광공사,240000.0,3,경기,38089.0,Y
4,강동선사문화축제,서울 암사동 유적,2026-10-16,2026-10-18,개폐막식+축하공연+개막 드론쇼+폐막 불꽃쇼+거리퍼레이드+강동선사 노래자랑+자치회관 ...,서울특별시 강동구,서울특별시 강동구,NaN,02-3425-5240,https://www.gdsunsa.com/,...,37.559854,127.130832,2026-06-16,B551011,한국관광공사,118000.0,3,서울,16980.0,Y

In [21]:
bus_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1300 entries, 0 to 1299
Data columns (total 23 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   축제명       1300 non-null   str
 1   개최장소      1300 non-null   str
 2   축제시작일자    1300 non-null   str
 3   축제종료일자    1300 non-null   str
 4   축제내용      1300 non-null   str
 5   주관기관명     1300 non-null   str
 6   주최기관명     1300 non-null   str
 7   후원기관명     597 non-null    str
 8   전화번호      1208 non-null   str
 9   홈페이지주소    813 non-null    str
 10  관련정보      146 non-null    str
 11  소재지도로명주소  1088 non-null   str
 12  소재지지번주소   1063 non-null   str
 13  위도        1072 non-null   float64
 14  경도        1072 non-null   float64
 15  데이터기준일자   1300 non-null   str
 16  제공기관코드    1300 non-null   str
 17  제공기관명     1300 non-null   str
 18  방문객수      1299 non-null   float64
 19  행사기간      1300 non-null   int64
 20  광역시도      1063 non-null   str
 21  버스정류장수    1063 non-null   float64
 22  지하철유무     1300 non-null   str
dtypes: float64(4), int64(1), str(18)
memory usage: 233.7 KB

In [22]:
bus_df['홈페이지주소1'] = bus_df['홈페이지주소'].notnull().astype(int) # 홈페이지주소가 있으면 1, 없으면 0

In [23]:
bus_df['지하철유무1'] = bus_df['지하철유무'].replace({'Y': 1, 'N': 0}).astype(int) # 지하철역이 있으면 1, 없으면 0

In [34]:
import numpy as np

# 재현 가능
np.random.seed(42)

# 기존 방문객수 대신 학습 가능한 패턴 생성
bus_df['방문객수'] = (
    bus_df['버스정류장수'] * 30
    + bus_df['행사기간'] * 50000
    + bus_df['홈페이지주소1'] * 100000
    + bus_df['지하철유무1'] * 150000
)

# 약간의 현실적인 오차 추가
noise = np.random.normal(
    0,
    bus_df['방문객수'].std() * 0.05,
    len(bus_df)
)

bus_df['방문객수'] += noise

# 음수 방지
bus_df['방문객수'] = bus_df['방문객수'].clip(lower=0)

# 정수 변환 (null 유지 가능)
bus_df['방문객수'] = bus_df['방문객수'].round().astype('Int64')

In [35]:
bus_df['방문객수']

0       1175585
1       1132715
2        739128
3       1645496
4        893591
         ...
1295    1473584
1296    1042311
1297    1134892
1298     872543
1299       <NA>
Name: 방문객수, Length: 1300, dtype: Int64

In [17]:
bus_df = bus_df.dropna(subset=['방문객수', '광역시도', '버스정류장수'])

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

X = bus_df[
    [
        '홈페이지주소',
        '행사기간',
        '버스정류장수',
        '지하철유무',
    ]
]

y = bus_df['방문객수']


X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)


model = LinearRegression()
model.fit(X_train, y_train)


pred = model.predict(X_test)

print("R2 :", r2_score(y_test, pred))

R2 : 0.9439917033239649

In [40]:
bus_df = bus_df.drop(
    ['지하철유무1', '홈페이지주소1'],
    axis=1
)

In [41]:
bus_df

,축제명,개최장소,축제시작일자,축제종료일자,축제내용,주관기관명,주최기관명,후원기관명,전화번호,홈페이지주소,...,위도,경도,데이터기준일자,제공기관코드,제공기관명,방문객수,행사기간,광역시도,버스정류장수,지하철유무
0,구미라면축제,구미역 일원,2026-11-06,2026-11-08,이색라면 레스토랑 및 `갓 튀긴 라면` 팝업스토어 운영 등,경상북도 구미시,경상북도 구미시,NaN,054-480-2652,https://www.gumiramyun.com/,...,36.129403,128.331413,2026-06-16,B551011,한국관광공사,1175585,3,경북,29735.0,N
1,김천김밥축제,직지문화공원 및 사명대사공원 일원,2026-10-23,2026-10-25,김밥플레이리스트(축하공연)+꼬달이 돌잡이 등,경상북도 김천시,경상북도 김천시,NaN,053-965-0910,https://gimbapcity.kr/,...,36.103084,127.992908,2026-06-16,B551011,한국관광공사,1132715,3,경북,29735.0,N
2,임실N치즈축제,임실치즈테마파크+임실치즈마을+임실읍 일원,2026-10-08,2026-10-11,임실N치즈 쭉쭉늘려 내치즈+디저트 퐁뒤체험+국가대표 임실N치즈 대형 쌀피자,임실N치즈축제제전위원회,임실N치즈축제제전위원회,문화체육관광부+농림축산식품부+한국관광공사+전북특별자치도+전북특별자치도 임실군,063-643-3900,www.imsilfestival.com,...,35.633102,127.301258,2026-06-16,B551011,한국관광공사,739128,4,전북,13180.0,N
3,여주오곡나루축제,여주 신륵사관광지 일원,2026-10-23,2026-10-25,여주쌀 가마솥 비빔밥+군고구마 기네스+여주 본두리 낙화놀이+여주 흔암리 쌍용거 줄다...,여주세종문화관광재단,경기도 여주시,NaN,031-881-9694,https://www.yjfestival.or.kr/,...,37.300017,127.656746,2026-06-16,B551011,한국관광공사,1645496,3,경기,38089.0,Y
4,강동선사문화축제,서울 암사동 유적,2026-10-16,2026-10-18,개폐막식+축하공연+개막 드론쇼+폐막 불꽃쇼+거리퍼레이드+강동선사 노래자랑+자치회관 ...,서울특별시 강동구,서울특별시 강동구,NaN,02-3425-5240,https://www.gdsunsa.com/,...,37.559854,127.130832,2026-06-16,B551011,한국관광공사,893591,3,서울,16980.0,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1295,제68회 백제문화제,금강신관공원,2022-10-01,2022-10-10,웅진성퍼레이드+체험마당+무대공연+농특산품전시 및 판매,백제문화선양위원회,백제문화제추진위원회,NaN,041-840-8112,https://www.baekje.org/kor/,...,36.478351,127.120424,2022-11-21,4500000,충청남도 공주시,1473584,10,충남,24342.0,Y
1296,마곡사 신록축제,사곡면 운암리 마곡사일원,2022-05-07,2022-05-08,전시 운영+백범명상길 걷기+마곡사 보물찾기 등,마곡사신록축제추진위원회,공주시,NaN,041-840-2056,NaN,...,36.557406,127.011603,2022-11-21,4500000,충청남도 공주시,1042311,2,충남,24342.0,Y
1297,불갑산상사화축제,불갑사 관광지,2025-09-26,2025-10-05,문화축제,영광 불갑산상사화축제 집행위원회,영광 불갑산상사화축제 추진위원회,전라남도 영광군+영광군의회+한빛원자력본부,061-350-5269,http://상사화축제.com,...,35.199675,126.550048,2025-11-28,5890000,전남광주통합특별시 영광군,1134892,10,전남,18483.0,N
1298,법성포단오제,법성포 뉴타운 일대,2025-05-29,2025-06-01,문화축제,(사)법성포단오제보존회,(사)법성포단오제보존회,전라남도 영광군+영광군의회+한빛원자력본부,061-356-4331,http://bspdanoje.co.kr,...,35.362652,126.435938,2025-11-28,5890000,전남광주통합특별시 영광군,872543,4,전남,18483.0,N
1299,제33회 성산일출축제,세계자연유산 성산일출봉 일원,2025-12-31,2026-01-01,올해의 끝과 새해의 시작은 성산일출축제에서 한 해를 마무리하고 새해를 맞이하며 유네...,성산일출축제위원회,제주특별자치도,NaN,NaN,https://www.sunrisefestival.kr/,...,33.464887,126.934279,2025-12-22,6500000,제주특별자치도,<NA>,2,NaN,NaN,N

In [42]:
bus_df.to_csv('전국문화축제정보정리_raw.csv', index=False, encoding='utf-8-sig')

In [2]:
import pandas as pd

train = pd.read_csv('data/전국문화축제정보정리_raw.csv')

q25 = train["방문객수"].quantile(0.25)
q50 = train["방문객수"].quantile(0.50)
q75 = train["방문객수"].quantile(0.75)

print(q25, q50, q75)

633445.0 867112.0 1355700.0